// Generated by nuxt-site-config

declare module 'nitropack' {
  interface NitroRouteRules {
    site?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface NitroRouteConfig {
    site?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfig
  }
  interface NitroRuntimeHooks {
    'site-config:init': (ctx: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').HookSiteConfigInitContext) => void | Promise<void>
  }
}

declare module 'h3' {
  interface H3EventContext {
    siteConfig: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
    siteConfigNitroOrigin: string
  }
}

declare module 'nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface Nuxt {
    _siteConfig?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
  }
}

declare module '@nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface Nuxt {
    _siteConfig?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
  }
}
declare module 'nuxt/app' {
  interface NuxtApp {
     $nuxtSiteConfig: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigResolved
  }
}
declare module '#app' {
  interface NuxtApp {
    $nuxtSiteConfig: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigResolved
  }
}
declare global {
  interface Window {
    __NUXT_SITE_CONFIG__: import('../../node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_nuxt@3.9.1_postcss@8.4._qnvdeqbxcbpceezsdwz4vkhkbi/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigResolved
  }
}

export {}
