// Generated by @nuxtjs/sitemap

declare module 'nitropack' {
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.0.3_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_h3@1.10.0_nuxt@3.9.1_pos_kmwdujkdo63hiqnuilvsr3qv4m/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.0.3_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_h3@1.10.0_nuxt@3.9.1_pos_kmwdujkdo63hiqnuilvsr3qv4m/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.0.3_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_h3@1.10.0_nuxt@3.9.1_pos_kmwdujkdo63hiqnuilvsr3qv4m/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.0.3_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_h3@1.10.0_nuxt@3.9.1_pos_kmwdujkdo63hiqnuilvsr3qv4m/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
  }
}
declare module 'vue-router' {
    interface RouteMeta {
        sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.0.3_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.14_h3@1.10.0_nuxt@3.9.1_pos_kmwdujkdo63hiqnuilvsr3qv4m/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
    }
}

export {}
